import sys
print(sys.version)
print(sys.path)
print(sys.platform)
print(sys.argv)
print(sys.executable)
print(sys.modules)
print(sys.getdefaultencoding())
print(sys.getfilesystemencoding())
print(sys.getrecursionlimit())
print(sys.getsizeof(1))
print(sys.getsizeof('a'))
print(sys.getsizeof([]))
print(sys.getsizeof({}))
print(sys.getsizeof(()))
print(sys.getsizeof(set()))
