''' Problem Statement
In Fibonacci sequence, next term is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
> 1, 2, 3, 5, 8, 13, 21, 34, 55, 89

Make two functions that consider only odd and even numbers, respectively in Fibonacci sequence upto a max limit and return their sum

Parameters:
> start - a tuple containing two numbers to start the sequence. Default value = [0, 1]
> max - maximum limit of fibonacci sequence
> contraint - 0 to add all terms; 1 to add odd terms only; 2 to add even terms only

Test:
sum of all odd  terms in the Fibonacci sequence whose values do not exceed four million
sum of all even terms in the Fibonacci sequence whose values do not exceed four million

Note: Optimsed function for origional Fibonacci sequence for even terms in last
'''

def check(num:int, kind:int) -> int:
    if kind==0:
        return num
    if kind==1 and num%2 != 0:
        return num
    if kind==2 and num%2 == 0:
        return num
    return 0

def sum_fibonacci(start:tuple, max:int, kind:int) -> int:
    total = 0
    for N in start:
        total += check(N, kind)

    num1, num2 = start
    while num2 < max:
        num1, num2 = num2, num1+num2
        total += check(num2, kind)

    return total

start = (1,1)
max = 4000000
#print('sum of odd  terms:', sum_fibonacci(start, max, 1))
#print('sum of even terms:', sum_fibonacci(start, max, 2))


# Particularly for even terms in origional Fibonacci sequence
def fibonacci_sum_even(max:int) -> int:
    total= 0
    num1 = num2 = 1
    num3 = 2
    while num3 < max:
        total+=num3
        num1= num2+num3
        num2= num3+num1
        num3= num1+num2

    return total

print('sum of even terms:', fibonacci_sum_even(max))
